# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4837beb0fcd24f046277f3fc15a0aa9e7ed69cdd5841538d6fb074d63fce5b652a3de19eaddc6bd4522ba1849ff2399a72253cb1d170ab2ec5be62c71d9b17f

test:
  secret_key_base: 6544525bfabf972cc9b8754db8c94cb29bd21755ac3835040a1aa6b4b7c936d4c45c6eef36248ef91e221dc6117c98a528f0b81ca5c835ddcf920c7498b46ef5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
